---
- name: Create /etc/vmware
  file:
    path: /etc/vmware
    owner: root
    group: root
    mode: "0755"
    state: directory

- name: Create /var/lib/vmware
  file:
    path: /var/lib/vmware
    owner: root
    group: root
    mode: "0755"
    state: directory

- name: Copy management network link configuration
  copy:
    src: files/usr/lib/systemd/network/10-management.link
    dest: /usr/lib/systemd/network/10-management.link
    owner: systemd-network
    group: systemd-network
    mode: "0644"
  when: ansible_default_ipv4.alias != "management"

- name: Copy workload network link configuration
  copy:
    src: files/usr/lib/systemd/network/10-workload.link
    dest: /usr/lib/systemd/network/10-workload.link
    owner: systemd-network
    group: systemd-network
    mode: "0644"
  when: ansible_workload is undefined

- name: Copy frontend network link configuration
  copy:
    src: files/usr/lib/systemd/network/10-frontend.link
    dest: /usr/lib/systemd/network/10-frontend.link
    owner: systemd-network
    group: systemd-network
    mode: "0644"
  when: ansible_frontend is undefined

- name: Generate new initrd image containing our link files
  shell:
    cmd: /usr/bin/dracut --add network --rebuild /boot/initrd.img-$(uname -r)
  when: ansible_default_ipv4.alias != "management"

- name: Copy frontend network configuration
  template:
    src: frontend.j2
    dest: /etc/systemd/network/10-frontend.network
    owner: systemd-network
    group: systemd-network
    mode: "0644"

- name: Copy management network configuration
  template:
    src: management.j2
    dest: /etc/systemd/network/10-management.network
    owner: systemd-network
    group: systemd-network
    mode: "0644"

- name: Copy workload network configuration
  template:
    src: workload.j2
    dest: /etc/systemd/network/10-workload.network
    owner: systemd-network
    group: systemd-network
    mode: "0644"

- name: Reboot system
  reboot:
    msg: "Reboot initiated by Ansible"
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 0
    post_reboot_delay: 0
    test_command: whoami
  when: ansible_default_ipv4.alias != "management"

- name: Regather facts to discover new interface names
  setup:
    gather_timeout: 30
  when: ansible_default_ipv4.alias != "management"

- name: Restart systemd-network service
  systemd:
    name: systemd-networkd
    state: restarted
  when: ansible_default_ipv4.alias == "management"

- name: Retrieve management MAC Address
  debug: msg="{{ hostvars[inventory_hostname].ansible_default_ipv4.macaddress }}"

- name: Retrieve frontend MAC Address
  debug: msg="{{ hostvars[inventory_hostname].ansible_frontend.macaddress }}"

- name: Retrieve management MAC Address
  debug: msg="{{ hostvars[inventory_hostname].ansible_workload.macaddress }}"

- name: Check if anyiproutectl exists
  ansible.builtin.stat:
    path: /usr/local/bin/anyiproutectl
  register: anyip_script

- name: Check if routetablectl exists
  ansible.builtin.stat:
    path: /usr/local/bin/routetablectl
  register: route_script

- name: Flush existing VIP CIDR routes
  command: anyiproutectl down
  when: anyip_script.stat.exists

- name: Flush existing routing tables
  command: routetablectl down
  when: route_script.stat.exists

- name: Create anyiproutectl script
  copy:
    src: files/var/lib/vmware/anyiproutectl.sh
    dest: /var/lib/vmware/anyiproutectl.sh
    owner: root
    group: root
    mode: "0744"

- name: Create anyip-routes service
  copy:
    src: files/etc/systemd/system/anyip-routes.service
    dest: /etc/systemd/system/anyip-routes.service
    owner: root
    group: root
    mode: "0644"

- name: Enable anyip-routes service
  systemd:
    name: anyip-routes
    enabled: yes
    daemon_reload: yes
    state: stopped

- name: Generate frontend VIP CIDR to anyip-routes.cfg using template
  template:
    src: anyiproute.j2
    dest: /etc/vmware/anyip-routes.cfg
    owner: root
    group: root
    mode: "0644"

- name: Create symbolic link for anyiproutectl
  command: ln -sf /var/lib/vmware/anyiproutectl.sh /usr/local/bin/anyiproutectl
  when: not anyip_script.stat.exists

- name: Create routetablectl script
  copy:
    src: files/var/lib/vmware/routetablectl.sh
    dest: /var/lib/vmware/routetablectl.sh
    owner: root
    group: root
    mode: "0744"

- name: Create route-tables service
  copy:
    src: files/etc/systemd/system/route-tables.service
    dest: /etc/systemd/system/route-tables.service
    owner: root
    group: root
    mode: "0644"

- name: Enable route-tables service
  systemd:
    name: route-tables
    enabled: yes
    daemon_reload: yes
    state: stopped

- name: Generate route table to route-tables.cfg using template
  template:
    src: routetable.j2
    dest: /etc/vmware/route-tables.cfg
    owner: root
    group: root
    mode: "0644"

- name: Create symbolic link for routetablectl
  command: ln -sf /var/lib/vmware/routetablectl.sh /usr/local/bin/routetablectl
  when: not route_script.stat.exists

- name: Apply new VIP CIDR routes
  command: anyiproutectl up
  when: anyip_script.stat.exists

- name: Apply new routing tables
  command: routetablectl up
  when: route_script.stat.exists

- name: Ensure anyip-routes service is restarted successfully
  systemd:
    name: anyip-routes
    state: restarted

- name: Ensure route-tables service is restarted successfully
  systemd:
    name: route-tables
    state: restarted
