---
- name: Create /etc/vmware
  file:
    path: /etc/vmware
    owner: root
    group: root
    mode: "0755"
    state: directory

- name: Create /var/lib/vmware
  file:
    path: /var/lib/vmware
    owner: root
    group: root
    mode: "0755"
    state: directory

- name: Copy management network link configuration
  copy:
    src: files/usr/lib/systemd/network/10-management.link
    dest: /usr/lib/systemd/network/10-management.link
    owner: systemd-network
    group: systemd-network
    mode: "0644"

- name: Copy workload network link configuration
  copy:
    src: files/usr/lib/systemd/network/10-workload.link
    dest: /usr/lib/systemd/network/10-workload.link
    owner: systemd-network
    group: systemd-network
    mode: "0644"

- name: Copy frontend network link configuration
  copy:
    src: files/usr/lib/systemd/network/10-frontend.link
    dest: /usr/lib/systemd/network/10-frontend.link
    owner: systemd-network
    group: systemd-network
    mode: "0644"

- name: Generate new initrd image containing our link files
  shell:
    cmd: /usr/bin/dracut --add network --rebuild /boot/initrd.img-$(uname -r)

- name: Create anyiproutectl script
  copy:
    src: files/var/lib/vmware/anyiproutectl.sh
    dest: /var/lib/vmware/anyiproutectl.sh
    owner: root
    group: root
    mode: "0744"

- name: Create anyip-routes service
  copy:
    src: files/etc/systemd/system/anyip-routes.service
    dest: /etc/systemd/system/anyip-routes.service
    owner: root
    group: root
    mode: "0644"

- name: Enable anyip-routes service
  systemd:
    name: anyip-routes
    enabled: yes
    daemon_reload: yes
    state: stopped

- name: Create routetablectl script
  copy:
    src: files/var/lib/vmware/routetablectl.sh
    dest: /var/lib/vmware/routetablectl.sh
    owner: root
    group: root
    mode: "0744"

- name: Create route-tables service
  copy:
    src: files/etc/systemd/system/route-tables.service
    dest: /etc/systemd/system/route-tables.service
    owner: root
    group: root
    mode: "0644"

- name: Enable route-tables service
  systemd:
    name: route-tables
    enabled: yes
    daemon_reload: yes
    state: stopped

- name: Copy frontend network configuration
  template:
    src: frontend.j2
    dest: /etc/systemd/network/10-frontend.network
    owner: systemd-network
    group: systemd-network
    mode: "0644"

- name: Copy management network configuration
  template:
    src: management.j2
    dest: /etc/systemd/network/10-management.network
    owner: systemd-network
    group: systemd-network
    mode: "0644"

- name: Copy workload network configuration
  template:
    src: workload.j2
    dest: /etc/systemd/network/10-workload.network
    owner: systemd-network
    group: systemd-network
    mode: "0644"

- name: Reboot system
  reboot:
    msg: "Reboot initiated by Ansible"
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 0
    post_reboot_delay: 0
    test_command: whoami
