---
- name: Ensure directories exist
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  with_items:
    - "{{ ssl_cert_path }}"
    - "{{ ssl_key_path }}"

- name: Check if Private Key file exists
  ansible.builtin.stat:
    path: "{{ ssl_key_path }}/{{ ssl_cert_name }}.key"
  register: key

- name: Generate Private Key
  community.crypto.openssl_privatekey:
    path: "{{ ssl_key_path }}/{{ ssl_cert_name }}.key"
    size: 4096
    type: RSA
    mode: '0600'
  when: not key.stat.exists

- name: Generate CSR with v3 extensions
  community.crypto.openssl_csr:
    path: "{{ ssl_cert_path }}/{{ ssl_cert_name }}.csr"
    privatekey_path: "{{ ssl_key_path }}/{{ ssl_cert_name }}.key"
    common_name: "{{ ssl_common_name }}"
    organization_name: "{{ ssl_org_name }}"
    country_name: "{{ ssl_country }}"
    state_or_province_name: "{{ ssl_state }}"
    locality_name: "{{ ssl_locality }}"
    subject_alt_name: >-
      {{ (ssl_dns_alt_names | map('regex_replace', '^', 'DNS:') | list) +
         ['IP:' + management_ipv4, 'IP:' + frontend_ipv4, 'IP:' + workload_ipv4] }}

    key_usage:
      - digitalSignature
      - keyEncipherment
    extended_key_usage:
      - serverAuth

- name: Generate Self-Signed Certificate
  community.crypto.x509_certificate:
    path: "{{ ssl_cert_path }}/{{ ssl_cert_name }}.crt"
    csr_path: "{{ ssl_cert_path }}/{{ ssl_cert_name }}.csr"
    privatekey_path: "{{ ssl_key_path }}/{{ ssl_cert_name }}.key"
    provider: selfsigned
    selfsigned_not_after: "{{ ssl_valid_days }}"
    mode: '0644'

- name: Combine Key and Cert using shell
  shell: |
    cat {{ ssl_key_path }}/{{ ssl_cert_name }}.key {{ ssl_cert_path }}/{{ ssl_cert_name }}.crt > {{ ssl_cert_path }}/{{ ssl_cert_name }}.pem
    chmod 600 {{ ssl_cert_path }}/{{ ssl_cert_name }}.pem
  args:
    creates: "{{ ssl_cert_path }}/{{ ssl_cert_name }}.pem" 

- name: Restart haproxy.service
  systemd:
    name: haproxy
    state: restarted

- name: Restart dataplaneapi.service
  systemd:
    name: dataplaneapi
    state: restarted

