---
- name: Ensure CA directories exist
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  with_items:
    - "{{ ca_cert_path }}"
    - "{{ ca_key_path }}"

- name: Check if Private CA Key file exists
  stat:
    path: "{{ ca_key_path }}/{{ ca_cert_name }}.key"
  register: ca_key

- name: Generate Private CA Key
  community.crypto.openssl_privatekey:
    path: "{{ ca_key_path }}/{{ ca_cert_name }}.key"
    size: 4096
    type: RSA
    mode: '0600'
  when: not ca_key.stat.exists

- name: Check if CA CSR file exists
  stat:
    path: "{{ ca_cert_path }}/{{ ca_cert_name }}.csr"
  register: ca_csr

- name: Create CSR for CA
  community.crypto.openssl_csr:
    path: "{{ ca_cert_path }}/{{ ca_cert_name }}.csr"
    privatekey_path: "{{ ca_key_path }}/{{ ca_cert_name }}.key"
    common_name: "{{ ca_common_name }}"
    organization_name: "{{ ca_org_name }}"
    organizational_unit_name: "{{ ca_org_unit_name }}"
    country_name: "{{ ca_country }}"
    state_or_province_name: "{{ ca_state }}"
    locality_name: "{{ ca_locality }}"
    basic_constraints:
      - "CA:TRUE"
    basic_constraints_critical: true
    key_usage:
      - keyCertSign
      - cRLSign
    key_usage_critical: true
  when: not ca_csr.stat.exists

- name: Check if CA Cert file exists
  stat:
    path: "{{ ca_cert_path }}/{{ ca_cert_name }}.crt"
  register: ca_crt

- name: Sign the CA Certificate
  community.crypto.x509_certificate:
    path: "{{ ca_cert_path }}/{{ ca_cert_name }}.crt"
    csr_path: "{{ ca_cert_path }}/{{ ca_cert_name }}.csr"
    privatekey_path: "{{ ca_key_path }}/{{ ca_cert_name }}.key"
    provider: selfsigned
    selfsigned_not_after: "{{ ca_valid_days }}"
    mode: '0644'
  when: not ca_crt.stat.exists

- name: Ensure Cert directories exist
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  with_items:
    - "{{ ssl_cert_path }}"
    - "{{ ssl_key_path }}"

- name: Check if Private Key file exists
  stat:
    path: "{{ ssl_key_path }}/{{ ssl_cert_name }}.key"
  register: key

- name: Generate Private Key
  community.crypto.openssl_privatekey:
    path: "{{ ssl_key_path }}/{{ ssl_cert_name }}.key"
    size: 4096
    type: RSA
    mode: '0600'
  when: not key.stat.exists

- name: Check if CSR file exists
  stat:
    path: "{{ ssl_cert_path }}/{{ ssl_cert_name }}.csr"
  register: csr

- name: Generate CSR with v3 extensions
  community.crypto.openssl_csr:
    path: "{{ ssl_cert_path }}/{{ ssl_cert_name }}.csr"
    privatekey_path: "{{ ssl_key_path }}/{{ ssl_cert_name }}.key"
    common_name: "{{ ssl_common_name }}"
    organization_name: "{{ ssl_org_name }}"
    organizational_unit_name: "{{ ssl_org_unit_name }}"
    country_name: "{{ ssl_country }}"
    state_or_province_name: "{{ ssl_state }}"
    locality_name: "{{ ssl_locality }}"
    subject_alt_name: >-
      {{ (ssl_dns_alt_names | map('regex_replace', '^', 'DNS:') | list) +
      ['IP:127.0.0.1', 'IP:' + management_ipv4, 'IP:' + frontend_ipv4, 'IP:' + workload_ipv4] }}
    key_usage:
      - digitalSignature
      - keyEncipherment
    extended_key_usage:
      - serverAuth
  when: not csr.stat.exists

- name: Check if Cert file exists
  stat:
    path: "{{ ssl_cert_path }}/{{ ssl_cert_name }}.crt"
  register: crt

- name: Generate Self-Signed Certificate
  community.crypto.x509_certificate:
    path: "{{ ssl_cert_path }}/{{ ssl_cert_name }}.crt"
    csr_path: "{{ ssl_cert_path }}/{{ ssl_cert_name }}.csr"
    privatekey_path: "{{ ssl_key_path }}/{{ ssl_cert_name }}.key"
    ownca_path: "{{ ca_cert_path }}/{{ ca_cert_name }}.crt"
    ownca_privatekey_path: "{{ ca_key_path }}/{{ ca_cert_name }}.key"
    provider: ownca
    ownca_not_after: "{{ ssl_valid_days }}"
    mode: '0644'
  when: not crt.stat.exists

- name: Check if Cert.pem file exists
  stat:
    path: "{{ ssl_cert_path }}/{{ ssl_cert_name }}.crt"
  register: crt_pem

- name: Combine Key and Cert using shell
  shell: |
    cat {{ ssl_key_path }}/{{ ssl_cert_name }}.key {{ ssl_cert_path }}/{{ ssl_cert_name }}.crt > {{ ssl_cert_path }}/{{ ssl_cert_name }}.pem
    chmod 600 {{ ssl_cert_path }}/{{ ssl_cert_name }}.pem
  when: not crt_pem.stat.exists

- name: Restart haproxy.service
  systemd:
    name: haproxy
    state: restarted

- name: Restart dataplaneapi.service
  systemd:
    name: dataplaneapi
    state: restarted

