---
- name: Ensure net.ipv4.ip_forward sysctl is present
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    sysctl_set: yes
    reload: yes
    sysctl_file: "{{ sysctl_conf_file }}"

- name: Ensure net.ipv6.conf.all.forwarding sysctl is present
  sysctl:
    name: net.ipv6.conf.all.forwarding
    value: "0"
    state: present
    sysctl_set: yes
    reload: yes
    sysctl_file: "{{ sysctl_conf_file }}"

- name: Ensure IPv6 is disabled for all interfaces
  sysctl:
    name: net.ipv6.conf.all.disable_ipv6
    value: "1"
    state: present
    sysctl_set: yes
    reload: yes
    sysctl_file: "{{ sysctl_conf_file }}"

- name: Ensure IPv6 is disabled as the default
  sysctl:
    name: net.ipv6.conf.default.disable_ipv6
    value: "1"
    state: present
    sysctl_set: yes
    reload: yes
    sysctl_file: "{{ sysctl_conf_file }}"

- name: Bind SSH only to IPv4
  replace:
    path: /etc/ssh/sshd_config
    regexp: '^.*?AddressFamily.*$'
    replace: 'AddressFamily inet'

- name: Create new group haproxy
  group:
    name: haproxy

- name: Create new user haproxy
  user:
    name: haproxy
    system: yes
    groups:
      - users
      - haproxy

- name: Create HAproxy chroot dir
  file:
    path: /var/lib/haproxy
    state: directory
    owner: haproxy
    mode: '0755'

- name: Install inotify-tools
  command: tdnf install inotify-tools -y

- name: Disable and Stop Iptables service
  systemd:
    name: iptables
    enabled: no
    state: stopped

- name: Check if anyiproutectl exists
  ansible.builtin.stat:
    path: /usr/local/bin/anyiproutectl
  register: anyip_script

- name: Flush existing VIP CIDR routes
  command: anyiproutectl down
  when: anyip_script.stat.exists

- name: Check if routetablectl exists
  ansible.builtin.stat:
    path: /usr/local/bin/routetablectl
  register: route_script

- name: Flush existing routing tables
  command: routetablectl down
  when: route_script.stat.exists
