---
- name: Retrieve management MAC Address
  debug: msg="{{ hostvars[inventory_hostname].ansible_default_ipv4.macaddress }}"

- name: Retrieve frontend MAC Address
  debug: msg="{{ hostvars[inventory_hostname].ansible_frontend.macaddress }}"

- name: Retrieve management MAC Address
  debug: msg="{{ hostvars[inventory_hostname].ansible_workload.macaddress }}"

- name: Generate anyip-routes.cfg
  template:
    src: anyiproute.j2
    dest: /etc/vmware/anyip-routes.cfg
    owner: root
    group: root
    mode: "0644"

- name: Generate route-tables.cfg
  template:
    src: routetable.j2
    dest: /etc/vmware/route-tables.cfg
    owner: root
    group: root
    mode: "0644"

- name: Restart anyip-routes service
  systemd:
    name: anyip-routes
    state: restarted

- name: Restart route-tables service
  systemd:
    name: route-tables
    state: restarted
